export { default as HeaderComponent } from './header/header'
export { default as HomeContentComponent } from './homeContent/homeContent'
export { default as DishesContentComponent } from './dishesContent/dishesContent'
export { default as AboutContentComponent } from './aboutContent/aboutContent'
export { default as SpecContentComponent } from './specContent/specContent'
export { default as ReviewContentComponent } from './reviewContent/reviewContent'
export { default as InputContentComponent } from './inputComponent/inputComponent1'
export { default as FooterComponent } from './footerComponent/footerComponent'
export { default as LoaderComponent } from './loaderComponent/loaderComponent'

export { default as SectionComponent } from './section/section'
export { default as ButtonComponent } from './button/button'
export { default as TitleComponent } from './titleSection/titleSection'
export { default as BoxContainerComponent } from './boxContainer/boxContainer'
export { default as BoxStarComponent } from './boxStar/boxStar'
export { default as FormComponent } from './formComponent/formComponent'
